"""
Regulatory Examination Package — generate_regulatory_package()

Produces a self-contained, independently-verifiable JSON package that a regulator
can validate against the raw database without trusting this system.

Package contents
────────────────
1. complete_event_stream     — every event for the application, in order, with
                               full payloads and metadata. Includes all related
                               streams: loan, agent sessions, compliance, audit.
2. projection_states         — state of every projection as it existed at
                               examination_date (temporal query via ComplianceAuditView
                               and point-in-time event replay for ApplicationSummary).
3. integrity_verification    — result of run_integrity_check() at examination time,
                               including the full hash chain replay via verify_full_chain().
4. lifecycle_narrative       — plain-English, one-sentence-per-event summary of the
                               application lifecycle, generated by replaying events.
5. ai_participation_record   — model versions, confidence scores, and input_data_hashes
                               for every AI agent that participated in the decision.
6. package_metadata          — generation timestamp, examination_date, package_version,
                               and a SHA-256 hash of the entire package contents so the
                               regulator can verify the package has not been tampered with
                               after generation.

Independent verifiability
─────────────────────────
The package includes the raw SQL queries a regulator can run to independently
reconstruct each section from the database. This means the regulator does not
need to trust this system — they can verify the package against the raw DB.

The package_hash field is computed over the canonical JSON of all other sections
(sorted keys, no whitespace). A regulator who recomputes this hash from the
package contents can verify the package was not modified after generation.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any

from src.event_store import EventStore, RecordedEvent
from src.integrity.audit_chain import run_integrity_check, verify_full_chain
from src.projections.compliance_audit import ComplianceAuditViewProjection

# Package schema version — increment when the structure changes.
_PACKAGE_VERSION = "1.0.0"

# Human-readable narrative templates per event type.
# Each template receives the event payload as keyword arguments.
_NARRATIVE_TEMPLATES: dict[str, str] = {
    "ApplicationSubmitted": (
        "Application {application_id} was submitted by applicant {applicant_id} "
        "requesting ${requested_amount_usd:,.2f}."
    ),
    "CreditAnalysisRequested": (
        "Credit analysis was requested and assigned to agent {assigned_agent_id}."
    ),
    "CreditAnalysisCompleted": (
        "Agent {agent_id} (model {model_version}) completed credit analysis: "
        "risk tier {risk_tier}, recommended limit ${recommended_limit_usd:,.2f}, "
        "confidence {confidence_score}."
    ),
    "FraudScreeningCompleted": (
        "Agent {agent_id} completed fraud screening: score {fraud_score:.3f} "
        "(model {screening_model_version})."
    ),
    "ComplianceCheckRequested": (
        "Compliance review initiated under regulation {regulation_set_version}; "
        "required checks: {checks_required}."
    ),
    "ComplianceRulePassed": (
        "Compliance rule {rule_id} passed (regulation {rule_version})."
    ),
    "ComplianceRuleFailed": (
        "Compliance rule {rule_id} FAILED: {failure_reason}."
    ),
    "ComplianceClearanceIssued": (
        "Full compliance clearance issued — all required checks passed."
    ),
    "DecisionGenerated": (
        "Orchestrator {orchestrator_agent_id} generated decision: {recommendation} "
        "(confidence {confidence_score}, forced_refer={forced_refer})."
    ),
    "HumanReviewCompleted": (
        "Reviewer {reviewer_id} completed human review: {final_decision}"
        "{override_note}."
    ),
    "ApplicationApproved": (
        "Application APPROVED by {approved_by}: ${approved_amount_usd:,.2f} "
        "at {interest_rate:.2%} interest, effective {effective_date}."
    ),
    "ApplicationDeclined": (
        "Application DECLINED by {declined_by}. "
        "Reasons: {decline_reasons}. "
        "Adverse action notice required: {adverse_action_notice_required}."
    ),
    "AuditIntegrityCheckRun": (
        "Integrity check run: {events_verified_count} events verified, "
        "chain valid: {chain_valid}."
    ),
}


def _render_narrative_line(event: RecordedEvent) -> str:
    """Render a single plain-English sentence for one event."""
    template = _NARRATIVE_TEMPLATES.get(event.event_type)
    if template is None:
        return f"{event.event_type} occurred (stream_position={event.stream_position})."

    try:
        payload = dict(event.payload)
        # Special handling for HumanReviewCompleted override note
        if event.event_type == "HumanReviewCompleted":
            if payload.get("override"):
                payload["override_note"] = f" [OVERRIDE: {payload.get('override_reason', '')}]"
            else:
                payload["override_note"] = ""
        # Format lists as comma-separated strings
        for k, v in payload.items():
            if isinstance(v, list):
                payload[k] = ", ".join(str(x) for x in v)
        return template.format_map(payload)
    except (KeyError, ValueError):
        return f"{event.event_type} at stream_position={event.stream_position}."


def _serialise_event(event: RecordedEvent) -> dict[str, Any]:
    """Serialise a RecordedEvent to a JSON-safe dict."""
    return {
        "event_id": str(event.event_id),
        "stream_id": event.stream_id,
        "stream_position": event.stream_position,
        "global_position": event.global_position,
        "event_type": event.event_type,
        "event_version": event.event_version,
        "payload": event.payload,
        "metadata": event.metadata,
        "recorded_at": event.recorded_at.isoformat() if hasattr(event.recorded_at, "isoformat") else str(event.recorded_at),
    }


def _compute_package_hash(sections: dict[str, Any]) -> str:
    """
    Compute SHA-256 over the canonical JSON of all package sections.
    Canonical = sorted keys, no whitespace, UTF-8 encoded.
    The regulator can recompute this independently to verify package integrity.
    """
    canonical = json.dumps(sections, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


async def _load_all_related_streams(
    store: EventStore,
    application_id: str,
) -> dict[str, list[RecordedEvent]]:
    """
    Load all event streams related to this application:
    - loan-{id}           — primary application stream
    - compliance-{id}     — compliance record stream
    - audit-loan-{id}     — audit ledger stream
    - agent-*             — all agent session streams that reference this application

    Agent session streams are discovered by scanning the loan stream for
    CreditAnalysisCompleted events, which carry agent_id and session_id.
    """
    streams: dict[str, list[RecordedEvent]] = {}

    # Primary streams
    for stream_id in [
        f"loan-{application_id}",
        f"compliance-{application_id}",
        f"audit-loan-{application_id}",
    ]:
        events = await store.load_stream(stream_id)
        if events:
            streams[stream_id] = events

    # Discover agent session streams from the loan stream
    loan_events = streams.get(f"loan-{application_id}", [])
    agent_stream_ids: set[str] = set()
    for ev in loan_events:
        if ev.event_type == "CreditAnalysisCompleted":
            agent_id = ev.payload.get("agent_id", "")
            session_id = ev.payload.get("session_id", "")
            if agent_id and session_id:
                agent_stream_ids.add(f"agent-{agent_id}-{session_id}")
        elif ev.event_type == "DecisionGenerated":
            for session_stream in ev.payload.get("contributing_agent_sessions", []):
                agent_stream_ids.add(session_stream)

    for stream_id in sorted(agent_stream_ids):
        events = await store.load_stream(stream_id)
        if events:
            streams[stream_id] = events

    return streams


async def _build_projection_states_at(
    store: EventStore,
    application_id: str,
    examination_date: datetime,
    pool,
) -> dict[str, Any]:
    """
    Reconstruct projection states as they existed at examination_date.

    ApplicationSummary: replay loan stream events up to examination_date
    using a fresh in-memory projection (no DB writes).

    ComplianceAuditView: use get_compliance_at() which supports temporal queries
    via the compliance_audit_events table.
    """
    states: dict[str, Any] = {}

    # Normalise examination_date to UTC-aware for consistent comparison
    if examination_date.tzinfo is None:
        examination_date = examination_date.replace(tzinfo=timezone.utc)

    # ApplicationSummary — replay events up to examination_date
    loan_events = await store.load_stream(f"loan-{application_id}")
    events_at_date = [
        e for e in loan_events
        if (e.recorded_at.replace(tzinfo=timezone.utc)
            if e.recorded_at.tzinfo is None
            else e.recorded_at) <= examination_date
    ]

    # Build ApplicationSummary state by walking events
    app_state: dict[str, Any] = {"application_id": application_id}
    for ev in events_at_date:
        p = ev.payload
        match ev.event_type:
            case "ApplicationSubmitted":
                app_state.update({
                    "state": "Submitted",
                    "applicant_id": p.get("applicant_id"),
                    "requested_amount_usd": p.get("requested_amount_usd"),
                })
            case "CreditAnalysisRequested":
                app_state["state"] = "AwaitingAnalysis"
            case "CreditAnalysisCompleted":
                app_state.update({
                    "state": "AnalysisComplete",
                    "risk_tier": p.get("risk_tier"),
                    "confidence_score": p.get("confidence_score"),
                })
            case "ComplianceCheckRequested":
                app_state["state"] = "ComplianceReview"
            case "DecisionGenerated":
                app_state.update({
                    "state": "PendingDecision",
                    "decision": p.get("recommendation"),
                    "forced_refer": p.get("forced_refer"),
                })
            case "HumanReviewCompleted":
                final = p.get("final_decision", "")
                app_state["state"] = (
                    "ApprovedPendingHuman" if final == "APPROVE" else "DeclinedPendingHuman"
                )
                app_state["human_reviewer_id"] = p.get("reviewer_id")
            case "ApplicationApproved":
                app_state.update({
                    "state": "FinalApproved",
                    "approved_amount_usd": p.get("approved_amount_usd"),
                    "interest_rate": p.get("interest_rate"),
                })
            case "ApplicationDeclined":
                app_state.update({
                    "state": "FinalDeclined",
                    "decline_reasons": p.get("decline_reasons"),
                })
    states["ApplicationSummary"] = app_state

    # ComplianceAuditView — temporal query
    async with pool.acquire() as conn:
        compliance_proj = ComplianceAuditViewProjection()
        try:
            compliance_state = await compliance_proj.get_compliance_at(
                application_id, examination_date, conn
            )
            states["ComplianceAuditView"] = asdict(compliance_state)
        except Exception as exc:
            states["ComplianceAuditView"] = {"error": str(exc)}

    return states


def _build_ai_participation_record(
    streams: dict[str, list[RecordedEvent]],
) -> list[dict[str, Any]]:
    """
    Extract model versions, confidence scores, and input_data_hashes for every
    AI agent that participated in the decision.

    Sources:
    - CreditAnalysisCompleted on agent session streams
    - FraudScreeningCompleted on agent session streams
    - DecisionGenerated on the loan stream (orchestrator)
    """
    records: list[dict[str, Any]] = []
    seen: set[tuple[str, str, str]] = set()  # (agent_id, event_type, application_id)

    for stream_id, events in streams.items():
        for ev in events:
            p = ev.payload
            app_id = p.get("application_id", "")

            if ev.event_type == "CreditAnalysisCompleted":
                agent_id = p.get("agent_id", "")
                key = (agent_id, "CreditAnalysisCompleted", app_id)
                if key not in seen:
                    seen.add(key)
                    records.append({
                        "agent_id": agent_id,
                        "session_id": p.get("session_id", ""),
                        "role": "credit_analyst",
                        "event_type": "CreditAnalysisCompleted",
                        "application_id": app_id,
                        "model_version": p.get("model_version"),
                        "confidence_score": p.get("confidence_score"),
                        "input_data_hash": p.get("input_data_hash"),
                        "risk_tier": p.get("risk_tier"),
                        "recommended_limit_usd": p.get("recommended_limit_usd"),
                        "analysis_duration_ms": p.get("analysis_duration_ms"),
                        "stream_id": stream_id,
                        "stream_position": ev.stream_position,
                        "recorded_at": str(ev.recorded_at),
                    })

            elif ev.event_type == "FraudScreeningCompleted":
                agent_id = p.get("agent_id", "")
                key = (agent_id, "FraudScreeningCompleted", app_id)
                if key not in seen:
                    seen.add(key)
                    records.append({
                        "agent_id": agent_id,
                        "role": "fraud_screener",
                        "event_type": "FraudScreeningCompleted",
                        "application_id": app_id,
                        "screening_model_version": p.get("screening_model_version"),
                        "fraud_score": p.get("fraud_score"),
                        "anomaly_flags": p.get("anomaly_flags", []),
                        "input_data_hash": p.get("input_data_hash"),
                        "stream_id": stream_id,
                        "stream_position": ev.stream_position,
                        "recorded_at": str(ev.recorded_at),
                    })

            elif ev.event_type == "DecisionGenerated":
                orch_id = p.get("orchestrator_agent_id", "")
                key = (orch_id, "DecisionGenerated", app_id)
                if key not in seen:
                    seen.add(key)
                    records.append({
                        "agent_id": orch_id,
                        "role": "orchestrator",
                        "event_type": "DecisionGenerated",
                        "application_id": app_id,
                        "recommendation": p.get("recommendation"),
                        "confidence_score": p.get("confidence_score"),
                        "forced_refer": p.get("forced_refer"),
                        "model_versions": p.get("model_versions", {}),
                        "contributing_agent_sessions": p.get("contributing_agent_sessions", []),
                        "decision_basis_summary": p.get("decision_basis_summary", ""),
                        "stream_id": stream_id,
                        "stream_position": ev.stream_position,
                        "recorded_at": str(ev.recorded_at),
                    })

    return records


def _build_verification_queries(application_id: str) -> dict[str, str]:
    """
    SQL queries a regulator can run independently to verify each package section.
    These queries reconstruct the package contents directly from the raw database.
    """
    return {
        "complete_event_stream": (
            f"SELECT event_id, stream_id, stream_position, global_position, "
            f"event_type, event_version, payload, metadata, recorded_at "
            f"FROM events "
            f"WHERE stream_id IN ("
            f"  'loan-{application_id}', "
            f"  'compliance-{application_id}', "
            f"  'audit-loan-{application_id}'"
            f") "
            f"ORDER BY stream_id, stream_position;"
        ),
        "agent_sessions": (
            f"SELECT DISTINCT e.stream_id "
            f"FROM events e "
            f"WHERE e.stream_id LIKE 'agent-%' "
            f"  AND e.payload->>'application_id' = '{application_id}';"
        ),
        "integrity_chain": (
            f"SELECT payload->>'integrity_hash', payload->>'previous_hash', "
            f"payload->>'chain_valid', payload->>'events_verified_count' "
            f"FROM events "
            f"WHERE stream_id = 'audit-loan-{application_id}' "
            f"  AND event_type = 'AuditIntegrityCheckRun' "
            f"ORDER BY stream_position;"
        ),
        "compliance_state": (
            f"SELECT event_type, rule_id, rule_version, result, failure_reason, recorded_at "
            f"FROM compliance_audit_events "
            f"WHERE application_id = '{application_id}' "
            f"ORDER BY id;"
        ),
        "ai_participation": (
            f"SELECT payload->>'agent_id', payload->>'model_version', "
            f"payload->>'confidence_score', payload->>'input_data_hash', "
            f"payload->>'risk_tier', event_type, recorded_at "
            f"FROM events "
            f"WHERE event_type IN ('CreditAnalysisCompleted', 'FraudScreeningCompleted', 'DecisionGenerated') "
            f"  AND payload->>'application_id' = '{application_id}' "
            f"ORDER BY global_position;"
        ),
    }


async def generate_regulatory_package(
    store: EventStore,
    application_id: str,
    examination_date: datetime,
    pool,
) -> dict[str, Any]:
    """
    Generate a complete, self-contained regulatory examination package.

    The package is a JSON-serialisable dict containing:
    1. complete_event_stream     — all events across all related streams
    2. projection_states         — projection state at examination_date
    3. integrity_verification    — hash chain verification result
    4. lifecycle_narrative       — plain-English event-by-event summary
    5. ai_participation_record   — all AI agent contributions with model metadata
    6. verification_queries      — SQL for independent DB verification
    7. package_metadata          — generation info + SHA-256 package hash

    The package_hash in package_metadata is computed over sections 1–6,
    allowing the regulator to verify the package was not modified post-generation.
    """
    generated_at = datetime.now(timezone.utc)

    # ── 1. Load all related streams ──────────────────────────────────────────
    streams = await _load_all_related_streams(store, application_id)

    complete_event_stream: list[dict[str, Any]] = []
    for stream_id in sorted(streams.keys()):
        for ev in streams[stream_id]:
            complete_event_stream.append(_serialise_event(ev))

    # ── 2. Projection states at examination_date ─────────────────────────────
    projection_states = await _build_projection_states_at(
        store, application_id, examination_date, pool
    )

    # ── 3. Integrity verification ────────────────────────────────────────────
    integrity_result = await run_integrity_check(store, "loan", application_id)
    full_chain = await verify_full_chain(store, "loan", application_id)

    integrity_verification = {
        "latest_check": {
            "events_verified": integrity_result.events_verified,
            "integrity_hash": integrity_result.integrity_hash,
            "previous_hash": integrity_result.previous_hash,
            "chain_valid": integrity_result.chain_valid,
            "tamper_detected": integrity_result.tamper_detected,
            "audit_stream_version": integrity_result.audit_stream_version,
        },
        "full_chain_replay": [
            {
                "segment": i + 1,
                "events_verified": r.events_verified,
                "integrity_hash": r.integrity_hash,
                "previous_hash": r.previous_hash,
                "chain_valid": r.chain_valid,
                "tamper_detected": r.tamper_detected,
            }
            for i, r in enumerate(full_chain)
        ],
        "overall_chain_valid": all(r.chain_valid for r in full_chain),
    }

    # ── 4. Lifecycle narrative ───────────────────────────────────────────────
    loan_events = streams.get(f"loan-{application_id}", [])
    narrative_lines: list[str] = []
    for ev in loan_events:
        line = _render_narrative_line(ev)
        narrative_lines.append(
            f"[{ev.recorded_at}] (pos={ev.stream_position}) {line}"
        )

    lifecycle_narrative = {
        "application_id": application_id,
        "total_events": len(loan_events),
        "narrative": narrative_lines,
        "summary": (
            f"Application {application_id} has {len(loan_events)} events "
            f"on its primary stream. "
            + (
                f"Final state: {loan_events[-1].event_type}."
                if loan_events else "No events recorded."
            )
        ),
    }

    # ── 5. AI participation record ───────────────────────────────────────────
    ai_participation_record = _build_ai_participation_record(streams)

    # ── 6. Verification queries ──────────────────────────────────────────────
    verification_queries = _build_verification_queries(application_id)

    # ── 7. Package metadata + hash ───────────────────────────────────────────
    # Hash is computed over sections 1–6 before adding metadata
    sections_for_hash = {
        "complete_event_stream": complete_event_stream,
        "projection_states": projection_states,
        "integrity_verification": integrity_verification,
        "lifecycle_narrative": lifecycle_narrative,
        "ai_participation_record": ai_participation_record,
        "verification_queries": verification_queries,
    }
    package_hash = _compute_package_hash(sections_for_hash)

    package_metadata = {
        "application_id": application_id,
        "examination_date": examination_date.isoformat(),
        "generated_at": generated_at.isoformat(),
        "package_version": _PACKAGE_VERSION,
        "package_hash": package_hash,
        "hash_algorithm": "SHA-256",
        "hash_scope": "sections 1-6 (canonical JSON, sorted keys, no whitespace)",
        "streams_included": sorted(streams.keys()),
        "total_events_across_all_streams": len(complete_event_stream),
    }

    return {
        **sections_for_hash,
        "package_metadata": package_metadata,
    }
